[point_groups]
    head = ["LFHD", "RFHD", "RBHD", "LBHD", "LFHD"]
    shoulders = ["LSHO", "RSHO"]
    luarm = ["LUPA2", "LUPA3", "LUPA1"]
    larm = ["LFRA", "LWRB", ]
    ruarm = ["RUPA2", "RUPA3", "RUPA1"]
    rarm = ["RFRA", "RWRB"]
    lhand = ["LWRB", "LFIN"]
    rhand = ["RWRB", "RFIN"]
    hands = ["(L|R)WRB", ".FIN"]   # Utilizamos expresiones regulares para encontrar patrones

    objects = ["OBJ1", "OBJ2", "OBJ3", "OBJ4", "OBJ5", "OBJ6", "OBJA"]
    objects_re = ["OBJ[1-Z]"]

    lleg = ["LTHI", "LKNE", "LTIB", "LANK", "LHEE", "LTOE"]
    rleg = ["RTHI", "RKNE", "RTIB", "RANK", "RHEE", "RTOE"]
    ball = ["BALL"]

    errores = ["LWRB", "Rfemur.*"]

    demo_arms = ["RSJC", "RELJ"]
    demo_forearms = ["RELJ", "RWJC"]

    centro_masa = ["RUarmCM", "LUarmCM", "RFarmCM", "LFarmCM"]

[demo_arms.config]
    join_color = [190, 215, 20, 150]

[demo_forearms.config]
    join_color = [190, 215, 20, 150]

[centro_masa.config]
    point_color = [255, 255, 0]
    point_size = 2.0

[head.config]
    point_color = [255, 0, 0]
    point_size = 0.5 # Mitad del tamaño original
    join_color = [255, 128, 0]

[shoulders.config]
    point_color = [100, 100, 255]
    point_size = 2.0 # Doble del tamaño original

[larm.config]
    point_color = [255, 100, 100]
    point_size = 1.0
    join_color = [255, 100, 100]

[rarm.config]
    point_color = [255, 100, 100]
    point_size = 1.0
    join_color = [255, 100, 100]

[objects.config]
    point_color = [100, 100, 100]
    line_thickness = 1.5
    join_color = [100, 100, 100]

[ball.config]
    point_color = [255, 255, 255]
    point_size = 2.0

[config1]
    visible_points = [
        ["head"], 
        ["luarm"], ["larm"], ["ruarm"], ["rarm"], ["hands"], #"C7",
        ["lleg"], ["rleg"],
        ["shoulders"],
        ["objects_re"], "BALL",
        "LWRB"
    ]

    joins = [
        [["head"]],     # Unir todos los puntos de la cabeza
        [["luarm"]],
        [["larm"]],
        [["ruarm"]],
        [["rarm"]],
        [["lhand"]],
        [["rhand"]],
        ["LUPA1", "LFRA"],
        ["RUPA1", "RFRA"],
        [["shoulders"]],
        ["CLAV", "C7", "T10", "STRN", "CLAV"],
        ["ThoraxS", "ThoraxI", "AbdI"],
        ["RSHO", "LSHO"],
        ["LASI", "RASI", "RPSI", "LPSI", "LASI"],
        [["lleg"]],
        [["rleg"]],
        [["objects"]],
    ]

    vectors = [
        ["OBJ1", "LVelOBJ1"],
        ["OBJ2", "LVelOBJ2"],
        ["ThoraxC", "WThorax"],
    ]


[solo_objetos]
    visible_points = [["objects"], "BALL"]

    joins = [
        [["objects"]]
    ]

    vectors = [
        ["OBJ1", "LVelOBJ1", 1.5]
    ]
    
    point_color = [255, 0, 0]
    join_color = [255, 195, 0]
    line_thickness = 2.0
    point_size = 1.5

[arms_with_cones] # Personalizar los brazos con conos
    visible_points = [
        ["head"],
        
        "RSJC", "RELJ", "RWJC", "RFINJC", # Brazo derecho
        "LSJC", "LELJ", "LWJC", "LFINJC", # Brazo izquierdo

        "C7", "CLAV", "STRN", "T10",      # Tronco
        "RASI", "LASI", "LPSI", "RPSI",   # Pelvis

        "RHJC", "RKJC", "RAJC",           # Pierna derecha
        "LHJC", "LKJC", "LAJC",           # Pierna izquierda

        "RHEE", "RTOE",                   # Pie derecho
        "LHEE", "LTOE",                   # Pie izquierdo

        "OBJA", "ClubFace3", "ClubFace4", "ClubFace6", "ClubFace5" # Palo
        ]

    joins = [
        [["head"]],
        { points = [["demo_arms"]], shape = { type = "semicono", radius1 = 4.0, radius2 = 2.0 } }, # Brazo derecho
        { points = ["RELJ", "RWJC"], shape = { type = "semicono", radius1 = 4.0, radius2 = 2.0 } }, # Antebrazo derecho
        { points = ["LSJC", "LELJ", "LWJC"], shape = { type = "semicono", radius1 = 4.0, radius2 = 2.0 } }, # Brazo izquierdo
        { points = ["RWJC", "RFINJC"], shape = { type = "semicono", radius1 = 2.5, radius2 = 1.0 } },       # Antebrazo derecho
        { points = ["LWJC", "LFINJC"], shape = { type = "semicono", radius1 = 2.5, radius2 = 1.0 } },       # Antebrazo izquierdo
        ["C7", "CLAV", "STRN", "T10", "C7"],                                                                # Tronco
        ["RASI", "LASI", "LPSI", "RPSI", "RASI"],                                                           # Pelvis
        { points = ["RHJC", "RKJC", "RAJC"], shape = { type = "semicone", radius1 = 5.0, radius2 = 3.0 } }, # Pierna derecha
        { points = ["LHJC", "LKJC", "LAJC"], shape = { type = "semicone", radius1 = 5.0, radius2 = 3.0 } }, # Pierna izquierda
        ["RAJC", "RHEE", "RTOE"],                                                                           # Pie derecho
        ["LAJC", "LHEE", "LTOE"],                                                                           # Pie izquierdo
        ["OBJA", "ClubFace3"],                                                                              # Palo
        ["ClubFace3", "ClubFace4", "ClubFace6", "ClubFace5", "ClubFace3"]                                   # Palo
    ]

    vectors = [
        ["RUarmCM", ["RUarmIv", "RUarmJv"], 2.5],
        ["RUarmCM", "RUarmKv", 2.5],
    ]

    join_color = [0, 195, 250]
    line_thickness = 0.75
    point_size = 0.8

[arms_with_rectangular_prism]
    visible_points = [
        ["head"],
        
        "RSJC", "RELJ", "RWJC", "RFINJC", # Brazo derecho
        "LSJC", "LELJ", "LWJC", "LFINJC", # Brazo izquierdo

        "C7", "CLAV", "STRN", "T10",      # Tronco
        "RASI", "LASI", "LPSI", "RPSI",   # Pelvis

        "RHJC", "RKJC", "RAJC",           # Pierna derecha
        "LHJC", "LKJC", "LAJC",           # Pierna izquierda

        "RHEE", "RTOE",                   # Pie derecho
        "LHEE", "LTOE",                   # Pie izquierdo

        "OBJA", "ClubFace3", "ClubFace4", "ClubFace6", "ClubFace5" # Palo
        ]

    joins = [
        [["head"]],
        { points = ["RSJC", "RELJ"], shape = { type = "prism", width = 4.0, height = 2.0, vector = "RUarmCM" } }, # Brazo derecho
        { points = ["RELJ", "RWJC"], shape = { type = "prism", width = 4.0, height = 2.0, vector = "RFarmCM" } }, # Brazo derecho vector = "RFarmCM"
        { points = ["LSJC", "LELJ", "LWJC"], shape = { type = "prism", width = 4.0, height = 2.0 } }, # Brazo izquierdo
        { points = ["RWJC", "RFINJC"], shape = { type = "prism", width = 2.5, height = 1.0 } },       # Antebrazo derecho 
        { points = ["LWJC", "LFINJC"], shape = { type = "prism", width = 2.5, height = 1.0 } },       # Antebrazo izquierdo
        ["C7", "CLAV", "STRN", "T10", "C7"],                                                                # Tronco
        ["RASI", "LASI", "LPSI", "RPSI", "RASI"],                                                           # Pelvis
        { points = ["RHJC", "RKJC", "RAJC"], shape = { type = "prism", width = 5.0, height = 3.0 } }, # Pierna derecha
        { points = ["LHJC", "LKJC", "LAJC"], shape = { type = "prism", width = 5.0, height = 3.0 } }, # Pierna izquierda
        ["RAJC", "RHEE", "RTOE"],                                                                           # Pie derecho
        ["LAJC", "LHEE", "LTOE"],                                                                           # Pie izquierdo
        ["OBJA", "ClubFace3"],                                                                              # Palo
        ["ClubFace3", "ClubFace4", "ClubFace6", "ClubFace5", "ClubFace3"]                                   # Palo
    ]

    vectors = [
        ["RUarmCM", ["RUarmIv", "RUarmJv", "RUarmKv"], 2.5],
        ["RFarmCM", ["RFarmIv", "RFarmJv", "RFarmKv"], 1.5],
        ["LUarmCM", ["LUarmIv", "LUarmJv", "LUarmKv"], 2.5],
        ["LFarmCM", ["LFarmIv", "LFarmJv", "LFarmKv"], 1.5],        
    ]

    join_color = [250, 0, 250, 190]
    line_thickness = 0.5
    point_size = 0.8
