name: Rust

on:
  push:
    branches: '*'
    paths:
      - '**/*.rs'
  pull_request:
    branches: '*'

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install gcc pkg-config libasound2-dev libudev-dev

    - name: Build
      run: cargo build --verbose

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: rustfmt
    - name: Install dependencies
      run: cargo fetch
      
    - name: Run tests
      run: cargo test --verbose
    - name: Check formatting
      run: cargo fmt -- --check
